<?php

namespace App\Modules\Admin\app\Services\Plans;

use App\Modules\Admin\app\Models\Plans\FeaturePlan;
use App\Modules\Admin\app\Models\Plans\Plan;
use App\Modules\Base\app\DTO\DTOInterface;
use App\Modules\Base\app\Services\BaseService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class PlanService extends BaseService
{

    public function __construct()
    {
        parent::__construct(resolve(Plan::class));
    }

    /**
     * @throws \Throwable
     */
    public function store(DtoInterface $dto): \Illuminate\Database\Eloquent\Model
    {
        DB::beginTransaction();
        $plan =  parent::store($dto);

        $data = $dto->toArray();
        $plan->features()->sync($data["features"]);
        $plan->storeImages(media: $dto->image ?? null);
        DB::commit();
        return $plan;
    }

    public function delete(Model $model): bool
    {
        $model->features()->detach();
        return parent::delete($model); // TODO: Change the autogenerated stub
    }

    public function update(Model $model, DTOInterface $dto): Model
    {
        $model =  parent::update($model, $dto);
        $model->features()->detach();
        $model->features()->sync($dto->toArray()["features"]);
        $model->storeImages(media: $dto->image ?? null,update: true);
        return $model;
    }
}
